warning: in the working copy of 'build.gradle.kts', LF will be replaced by CRLF the next time Git touches it
[1mdiff --git a/build.gradle.kts b/build.gradle.kts[m
[1mindex 4d55533..ee27413 100644[m
[1m--- a/build.gradle.kts[m
[1m+++ b/build.gradle.kts[m
[36m@@ -23,6 +23,8 @@[m [mdependencies {[m
     implementation("org.springframework.boot:spring-boot-starter-data-jpa")[m
     implementation("org.springframework.boot:spring-boot-starter-validation")[m
     implementation("org.springframework.boot:spring-boot-starter-webmvc")[m
[32m+[m[32m    implementation("org.springframework.boot:spring-boot-starter-security")[m
[32m+[m[32m    testImplementation("org.springframework.boot:spring-boot-starter-security-test")[m
     compileOnly("org.projectlombok:lombok")[m
     developmentOnly("org.springframework.boot:spring-boot-devtools")[m
     runtimeOnly("com.h2database:h2")[m
[1mdiff --git a/src/main/java/com/henrikel/libraryapi/controller/LivroController.java b/src/main/java/com/henrikel/libraryapi/controller/LivroController.java[m
[1mindex 73dedfa..7820059 100644[m
[1m--- a/src/main/java/com/henrikel/libraryapi/controller/LivroController.java[m
[1m+++ b/src/main/java/com/henrikel/libraryapi/controller/LivroController.java[m
[36m@@ -1,8 +1,8 @@[m
 package com.henrikel.libraryapi.controller;[m
 [m
[31m-import com.henrikel.libraryapi.dto.LivroPatchDTO;[m
[31m-import com.henrikel.libraryapi.dto.LivroRequestDTO;[m
[31m-import com.henrikel.libraryapi.dto.LivroResponseDTO;[m
[32m+[m[32mimport com.henrikel.libraryapi.dto.livroDTOS.LivroPatchDTO;[m
[32m+[m[32mimport com.henrikel.libraryapi.dto.livroDTOS.LivroRequestDTO;[m
[32m+[m[32mimport com.henrikel.libraryapi.dto.livroDTOS.LivroResponseDTO;[m
 [m
 import com.henrikel.libraryapi.service.LivroService;[m
 import jakarta.validation.Valid;[m
[1mdiff --git a/src/main/java/com/henrikel/libraryapi/controller/UsuarioController.java b/src/main/java/com/henrikel/libraryapi/controller/UsuarioController.java[m
[1mindex a376c41..16cc490 100644[m
[1m--- a/src/main/java/com/henrikel/libraryapi/controller/UsuarioController.java[m
[1m+++ b/src/main/java/com/henrikel/libraryapi/controller/UsuarioController.java[m
[36m@@ -1,8 +1,8 @@[m
 package com.henrikel.libraryapi.controller;[m
 [m
[31m-import com.henrikel.libraryapi.dto.UsuarioPatchDto;[m
[31m-import com.henrikel.libraryapi.dto.UsuarioRequestDTO;[m
[31m-import com.henrikel.libraryapi.dto.UsuarioResponseDTO;[m
[32m+[m[32mimport com.henrikel.libraryapi.dto.usuarioDTOS.UsuarioPatchDto;[m
[32m+[m[32mimport com.henrikel.libraryapi.dto.usuarioDTOS.UsuarioRequestDTO;[m
[32m+[m[32mimport com.henrikel.libraryapi.dto.usuarioDTOS.UsuarioResponseDTO;[m
 import com.henrikel.libraryapi.service.UsuarioService;[m
 import jakarta.validation.Valid;[m
 import lombok.AllArgsConstructor;[m
[36m@@ -25,28 +25,34 @@[m [mpublic class UsuarioController {[m
     public Page<UsuarioResponseDTO> listarUsuarios(@PageableDefault(size = 10, sort = "nome") Pageable pageable){[m
         return usuarioService.listarUsuarios(pageable);[m
     }[m
[32m+[m
     @PostMapping[m
     @ResponseStatus(HttpStatus.CREATED)[m
[31m-    public UsuarioResponseDTO salvarUsuario(@RequestBody @Valid UsuarioRequestDTO usuario){[m
[31m-        return usuarioService.salvar(usuario);[m
[32m+[m[32m    public UsuarioResponseDTO salvarAdmin(@RequestBody @Valid UsuarioRequestDTO usuario){[m
[32m+[m[32m        return usuarioService.salvarAdm(usuario);[m
     }[m
[32m+[m
     @DeleteMapping("/{id}")[m
     public ResponseEntity<Void> deletar(@PathVariable Long id){[m
         usuarioService.deletar(id);[m
         return ResponseEntity.noContent().build();[m
     }[m
[32m+[m
     @GetMapping("/nome")[m
     public List<UsuarioResponseDTO> buscarPorNome(@RequestParam String nome){[m
         return usuarioService.buscarUsuarioQuery(nome);[m
     }[m
[32m+[m
     @GetMapping("/{id}")[m
     public UsuarioResponseDTO buscarPorId(@PathVariable Long id){[m
         return usuarioService.buscarUsuario(id);[m
     }[m
[32m+[m
     @PutMapping("/{id}")[m
[31m-    public UsuarioResponseDTO alterarLivro(@RequestBody @Valid UsuarioRequestDTO dto, @PathVariable Long id){[m
[32m+[m[32m    public UsuarioResponseDTO alterarUsuario(@RequestBody @Valid UsuarioRequestDTO dto, @PathVariable Long id){[m
         return usuarioService.alterarUsuario(id, dto);[m
     }[m
[32m+[m
     @PatchMapping("/{id}")[m
     public UsuarioResponseDTO alterarAtributo(@RequestBody UsuarioPatchDto dto, @PathVariable Long id){[m
         return usuarioService.alterarAtributo(id, dto);[m
[1mdiff --git a/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroPatchDTO.java b/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroPatchDTO.java[m
[1mindex 90bc7af..f75ef5f 100644[m
[1m--- a/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroPatchDTO.java[m
[1m+++ b/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroPatchDTO.java[m
[36m@@ -1,9 +1,4 @@[m
[31m-package com.henrikel.libraryapi.dto;[m
[31m-[m
[31m-import jakarta.validation.constraints.NotBlank;[m
[31m-import jakarta.validation.constraints.NotNull;[m
[31m-import jakarta.validation.constraints.PastOrPresent;[m
[31m-import jakarta.validation.constraints.Size;[m
[32m+[m[32mpackage com.henrikel.libraryapi.dto.livroDTOS;[m
 [m
 import java.time.Year;[m
 [m
[1mdiff --git a/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroRequestDTO.java b/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroRequestDTO.java[m
[1mindex d664612..b21ecc2 100644[m
[1m--- a/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroRequestDTO.java[m
[1m+++ b/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroRequestDTO.java[m
[36m@@ -1,4 +1,4 @@[m
[31m-package com.henrikel.libraryapi.dto;[m
[32m+[m[32mpackage com.henrikel.libraryapi.dto.livroDTOS;[m
 [m
 import jakarta.validation.constraints.NotBlank;[m
 import jakarta.validation.constraints.NotNull;[m
[1mdiff --git a/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroResponseDTO.java b/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroResponseDTO.java[m
[1mindex e352288..bf2e798 100644[m
[1m--- a/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroResponseDTO.java[m
[1m+++ b/src/main/java/com/henrikel/libraryapi/dto/livroDTOS/LivroResponseDTO.java[m
[36m@@ -1,4 +1,4 @@[m
[31m-package com.henrikel.libraryapi.dto;[m
[32m+[m[32mpackage com.henrikel.libraryapi.dto.livroDTOS;[m
 [m
 import java.time.Year;[m
 [m
[1mdiff --git a/src/main/java/com/henrikel/libraryapi/dto/usuarioDTOS/UsuarioPatchDto.java b/src/main/java/com/henrikel/libraryapi/dto/usuarioDTOS/UsuarioPatchDto.java[m
[1mindex 747acd5..a764b19 100644[m
[1m--- a/src/main/java/com/henrikel/libraryapi/dto/usuarioDTOS/UsuarioPatchDto.java[m
[1m+++ b/src/main/java/com/henrikel/libraryapi/dto/usuarioDTOS/UsuarioPatchDto.java[m
[36m@@ -1,8 +1,7 @@[m
[31m-package com.henrikel.libraryapi.dto;[m
[32m+[m[32mpackage com.henrikel.libraryapi.dto.usuarioDTOS;[m
 [m
 import com.henrikel.libraryapi.model.Papel;[m
 import jakarta.validation.constraints.Email;[m
[31m-import jakarta.validation.constraints.NotBlank;[m
 import jakarta.validation.constraints.Size;[m
 [m
 public record UsuarioPatchDto([m
[1mdiff --git a/src/main/java/com/henrikel/libraryapi/dto/usuarioDTOS/UsuarioRequestDTO.java b/src/main/java/com/henrikel/libraryapi/dto/usuarioDTOS/UsuarioRequestDTO.java[m
[1mindex ff2cb49..e912096 100644[m
[1m--- a/src/main/java/com/henrikel/libraryapi/dto/usuarioDTOS/UsuarioRequestDTO.java[m
[1m+++ b/src/main/java/com/henrikel/libraryapi/dto/usuarioDTOS/UsuarioRequestDTO.java[m
[36m@@ -1,4 +1,4 @@[m
[31m-package com.henrikel.libraryapi.dto;[m
[32m+[m[32mpackage com.henrikel.libraryapi.dto.usuarioDTOS;[m
 [m
 import com.henrikel.libraryapi.model.Papel;[m
 import jakarta.validation.constraints.Email;[m
[36m@@ -15,7 +15,5 @@[m [mpublic record UsuarioRequestDTO(@NotBlank(message = "Nome é obrigatório")[m
                                 Stri